.PHONY: clean All

All:
	@echo "----------Building project:[ kit -  ]----------"
	@cd "kit" && "$(MAKE)" -f  "kit.mk"
clean:
	@echo "----------Cleaning project:[ kit -  ]----------"
	@cd "kit" && "$(MAKE)" -f  "kit.mk" clean
